version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    # environment: (Đã dùng env_file nên bỏ qua phần này cho gọn)
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - django_static:/app/static
    ports:
      - "8000:8000"

  frontend-builder:
    build: ./SyncNote-FE
    volumes:
      - frontend_build:/frontend_build
    # Lệnh build React và copy ra volume chung
    command: sh -c "npm install && npm run build && cp -r dist/* /frontend_build/"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
      - django_static:/app/static
    depends_on:
      - backend
      - frontend-builder

volumes:
  pgdata:
  django_static:
  frontend_build: